import { AnimatePresence, motion } from "motion/react";
import { Check } from "lucide-react";
import { useState } from "react";
import Button from "../components/ui/Button";
import Container from "../components/ui/Container";
import { useSeo } from "../hooks/useSeo";

export default function ContactPage() {
  useSeo("Start a project", "Tell NULL/FORM what you want to make possible."); const [sent, setSent] = useState(false);
  return <section className="contact-page"><Container><div className="contact-grid"><div className="contact-copy"><div className="section-tag"><span>CONTACT</span>NEW BUSINESS / 2026</div><h1>LET'S MAKE<br /><em>SOMETHING<br />IMPOSSIBLE.</em></h1><p>Tell us where you want to go. We will help you find the form, motion, and technology to get there.</p><a href="mailto:hello@nullform.studio">hello@nullform.studio</a></div><AnimatePresence mode="wait">{sent ? <motion.div className="contact-success" key="success" initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }}><span><Check /></span><h2>Signal received.</h2><p>Thanks—we'll be in touch soon.</p><button onClick={() => setSent(false)}>Send another note</button></motion.div> : <motion.form key="form" className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true); }} exit={{ opacity: 0, y: -20 }}><div className="form-row"><label><span>Your name</span><input required name="name" placeholder="Name" /></label><label><span>Email address</span><input required type="email" name="email" placeholder="you@company.com" /></label></div><label><span>Company / studio</span><input name="company" placeholder="Optional" /></label><div className="form-row"><label><span>Project type</span><select name="type" defaultValue=""><option value="" disabled>Select one</option><option>Interactive website</option><option>Digital product</option><option>3D experience</option><option>Creative development</option></select></label><label><span>Indicative budget</span><select name="budget" defaultValue=""><option value="" disabled>Select range</option><option>$20k–$40k</option><option>$40k–$80k</option><option>$80k+</option></select></label></div><label><span>Tell us about the idea</span><textarea required name="message" placeholder="What are we making possible?" rows={5} /></label><Button type="submit">Send project brief</Button><small>This form is a frontend demo. No data is sent or stored.</small></motion.form>}</AnimatePresence></div></Container></section>;
}
